// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations.ValuationDb
{
    [DbContext(typeof(ValuationDbContext))]
    [Migration("20251104043354_FxRates")]
    partial class FxRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PM.Domain.Entities.ValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ValuationSnapshots");
                });

            modelBuilder.Entity("PM.Domain.Values.AssetPrice", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "Date");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("PM.Domain.Values.FxRate", b =>
                {
                    b.Property<string>("FromCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("FromCurrency", "ToCurrency", "Date");

                    b.HasIndex("FromCurrency", "ToCurrency");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("PM.Domain.Entities.ValuationSnapshot", b =>
                {
                    b.OwnsOne("PM.Domain.Values.Money", "CashValue", b1 =>
                        {
                            b1.Property<Guid>("ValuationSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT");

                            b1.HasKey("ValuationSnapshotId");

                            b1.ToTable("ValuationSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("ValuationSnapshotId");
                        });

                    b.OwnsOne("PM.Domain.Values.Money", "IncomeForDay", b1 =>
                        {
                            b1.Property<Guid>("ValuationSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT");

                            b1.HasKey("ValuationSnapshotId");

                            b1.ToTable("ValuationSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("ValuationSnapshotId");
                        });

                    b.OwnsOne("PM.Domain.Values.Money", "SecuritiesValue", b1 =>
                        {
                            b1.Property<Guid>("ValuationSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT");

                            b1.HasKey("ValuationSnapshotId");

                            b1.ToTable("ValuationSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("ValuationSnapshotId");
                        });

                    b.OwnsOne("PM.Domain.Values.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("ValuationSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT");

                            b1.HasKey("ValuationSnapshotId");

                            b1.ToTable("ValuationSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("ValuationSnapshotId");
                        });

                    b.Navigation("CashValue");

                    b.Navigation("IncomeForDay");

                    b.Navigation("SecuritiesValue");

                    b.Navigation("Value")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
