// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20251104043321_SOMETEXT")]
    partial class SOMETEXT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialInstitution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("PM.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("PM.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HoldingId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PM.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.HasOne("PM.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Accounts")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PM.Domain.Entities.Asset", "_asset", b1 =>
                        {
                            b1.Property<int>("HoldingId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AssetClass")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AssetClass");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AssetCode");

                            b1.HasKey("HoldingId");

                            b1.ToTable("Holdings");

                            b1.WithOwner()
                                .HasForeignKey("HoldingId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("AssetHoldingId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("AssetCurrency");

                                    b2.HasKey("AssetHoldingId");

                                    b2.ToTable("Holdings");

                                    b2.WithOwner()
                                        .HasForeignKey("AssetHoldingId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Account");

                    b.Navigation("_asset");
                });

            modelBuilder.Entity("PM.Domain.Entities.Tag", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", null)
                        .WithMany("Tags")
                        .HasForeignKey("AccountId");

                    b.HasOne("PM.Domain.Entities.Holding", null)
                        .WithMany("Tags")
                        .HasForeignKey("HoldingId");
                });

            modelBuilder.Entity("PM.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PM.Domain.Values.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("AmountCurrency");

                                    b2.HasKey("MoneyTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyTransactionId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("PM.Domain.Values.Money", "Costs", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostAmount");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CostCurrency");

                                    b2.HasKey("MoneyTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyTransactionId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("PM.Domain.Values.Symbol", "Symbol", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AssetClass")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AssetClass");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AssetCode");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("SymbolTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Currency");

                                    b2.HasKey("SymbolTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("SymbolTransactionId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Costs");

                    b.Navigation("Symbol")
                        .IsRequired();
                });

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Tags");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PM.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
