// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AccountTag", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AccountTag");
                });

            modelBuilder.Entity("HoldingTag", b =>
                {
                    b.Property<int>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoldingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("HoldingTag");
                });

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialInstitution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("PM.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("PM.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HoldingId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PM.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AccountTag", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoldingTag", b =>
                {
                    b.HasOne("PM.Domain.Entities.Holding", null)
                        .WithMany()
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.HasOne("PM.Domain.Entities.Portfolio", null)
                        .WithMany("Accounts")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PM.Domain.Values.Instrument", "Instrument", b1 =>
                        {
                            b1.Property<int>("HoldingId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AssetClass")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("HoldingId");

                            b1.ToTable("Holdings");

                            b1.WithOwner()
                                .HasForeignKey("HoldingId");

                            b1.OwnsOne("PM.Domain.Values.Symbol", "Symbol", b2 =>
                                {
                                    b2.Property<int>("InstrumentHoldingId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("InstrumentHoldingId");

                                    b2.ToTable("Holdings");

                                    b2.WithOwner()
                                        .HasForeignKey("InstrumentHoldingId");
                                });

                            b1.Navigation("Symbol")
                                .IsRequired();
                        });

                    b.Navigation("Account");

                    b.Navigation("Instrument")
                        .IsRequired();
                });

            modelBuilder.Entity("PM.Domain.Entities.Tag", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", null)
                        .WithMany("Tags")
                        .HasForeignKey("AccountId");

                    b.HasOne("PM.Domain.Entities.Holding", null)
                        .WithMany("Tags")
                        .HasForeignKey("HoldingId");
                });

            modelBuilder.Entity("PM.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PM.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PM.Domain.Values.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MoneyTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyTransactionId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("PM.Domain.Values.Money", "Costs", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Currency", "Currency", b2 =>
                                {
                                    b2.Property<int>("MoneyTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MoneyTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyTransactionId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("PM.Domain.Values.Instrument", "Instrument", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AssetClass")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");

                            b1.OwnsOne("PM.Domain.Values.Symbol", "Symbol", b2 =>
                                {
                                    b2.Property<int>("InstrumentTransactionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("InstrumentTransactionId");

                                    b2.ToTable("Transactions");

                                    b2.WithOwner()
                                        .HasForeignKey("InstrumentTransactionId");
                                });

                            b1.Navigation("Symbol")
                                .IsRequired();
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Costs");

                    b.Navigation("Instrument")
                        .IsRequired();
                });

            modelBuilder.Entity("PM.Domain.Entities.Account", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Tags");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PM.Domain.Entities.Holding", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PM.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
